[package]
name = "ticket1"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.9.1"
scarb-version = "2.9.1"
sierra-version = "2.2.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }


[dev-dependencies]
cairo_test = "2.9.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.33.0" }  # Update to latest stable version



[[target.starknet-contract]]
sierra = true
casm = true